In [ ]:
# Name: Rupsa Karak     PRN:25070123098
# Experiment 9
# Aim: Study of NumPy Library

In [49]:
# Declaration of NumPy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

# Dimension of Array
print(a.ndim)
print(b.ndim)

# Shape
print(a.shape)
print(b.shape)

# Date type
print(a.dtype)
print(b.dtype)

# Size
print(a.size)
print(b.size)

# In built functions using NumPy
print(np.zeros((2,3)))

# ones
print(np.ones((2,3)))

# eye
print(np.eye((3)))

# arrange
np.arange(10,20,2)

# linspace
np.linspace(0,1,4)

# Sum and Multiplication in the matrix
print(a+5)
print(b*2)

# Mean
print(np.mean(a))

# Median
print(np.median(a))

# Standard Deviation
print(np.std(a))

# Max and Minimum value
print(np.max(a))
print(np.min(a))

# Sum
print(np.sum(a))

# Transpose
print(np.transpose(b))

#Sort
print(np.sort(b))
print(np.sort(a))

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64
7
6
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  6  15  25  35  45  55 505]
[[ 2  4  6]
 [ 8 10 12]]
93.0
30.0
166.88661677061722
500
1
651
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[  1  10  20  30  40  50 500]
